; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev-usb]
;platform = espressif32
platform = espressif32 @ ^6.7.0
board = esp32dev
framework = arduino

board_build.filesystem = littlefs
board_build.partitions = custom_ota.csv
monitor_speed = 115200
upload_speed = 460800
build_flags = 
    -DCONFIG_LITTLEFS_FOR_IDF_3_2
    -DMBEDTLS_CONFIG_FILE=\"mbedtls/esp_config.h\"
    -DLITTLEFS_PARTITION_NAME=\"littlefs\"    # ← wskazuje nazwę partycji
lib_deps = 
    einararnason/ArduinoQueue@^1.2.5
    bblanchon/ArduinoJson @ 6.21.5
    https://github.com/eModbus/eModbus.git
    OneWire=https://github.com/promillen/OneWire/archive/refs/heads/patch-1.zip
    milesburton/DallasTemperature@^3.9.1

[env:esp32dev-ota]
;platform = espressif32
platform = espressif32 @ ^6.7.0
board = esp32dev
framework = arduino
board_build.filesystem = littlefs
board_build.partitions = custom_ota.csv
monitor_speed = 115200
upload_protocol = espota
upload_port = 192.168.20.34
lib_deps = 
    ${env:esp32dev-usb.lib_deps}